### ISSUE TITLE
Events Screen

### ISSUE THREAD

**Issue by vis-123** [TeamStingers/StudentOrgManager#7]
get org events
add event item
admin and officer delete posts by clicking on name to get opts
everyone can view profile by clicking on name to get opts
officer and admins can view absences for each events => event absences screen

**Comment by swarlik** [comment]
event options:
- view absences (officers & admins only)
- delete event (officers & admins only)

**Comment by swarlik** [comment]
Also need add new event screen

**Comment by swarlik** [comment]
Everything is done, just need to figure out how to send date/time for event to database
